"""
Django settings for prp project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
import requests


# Domains of the application, takes a comma separated string.
APP_DOMAINS = [host.strip() for host in os.environ.get('APP_DOMAINS', 'localhost').split(',')]


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'okuut7a=^zeb3+ssb+-rewmk+*xi^t3-$ms3qg-7d50q^#z508'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = str(os.environ.get('DEBUG')).lower() in ['true', '1']

ALLOWED_HOSTS = APP_DOMAINS

# Special case for ECS instances, we need to add the internal IP address to
# the allowed hosts so the load balancer can perform health checks.
# AWS provides a special endpoint to query for that so we test for that and add
# it if found, if not do nothing. This will slow down restarts slightly locally
# so it will only perform the test if EC2_METADATA_LOCAL_IP is set.
EC2_METADATA_LOCAL_IP = str(os.environ.get('EC2_METADATA_LOCAL_IP')).lower() in ['true', '1']
if EC2_METADATA_LOCAL_IP:
    try:
        aws_url = 'http://169.254.169.254/latest/meta-data/local-ipv4'
        internal_ip = requests.get(aws_url, timeout=1).text
    except requests.exceptions.ConnectionError:
        pass
    else:
        ALLOWED_HOSTS.append(internal_ip)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'programmes.apps.ProgrammesConfig',
    'rest_framework',
    'corsheaders',

]

# Overrides the default auth model so TeamMember can be treated as admins
AUTH_USER_MODEL = 'programmes.TeamMember'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
#    'django.middleware.clickjacking.XFrameOptionsMiddleware' # XFrame with 'sameorigin' causes errors in getting resource requests. Must fix before production

]

ROOT_URLCONF = 'prp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'prp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('PG_DB'),
        'USER': os.environ.get('PG_USER'),
        'PASSWORD': os.environ.get('PG_PASS'),
        'HOST': os.environ.get('PG_HOST'),
        'PORT': os.environ.get('PG_PORT', '5432'), # 5432 is the default PostgreSQL port

    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Pacific/Auckland'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# Django REST Framework
REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'rest_framework_json_api.exceptions.exception_handler',
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework_json_api.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser'
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework_json_api.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    'DEFAULT_METADATA_CLASS': 'rest_framework_json_api.metadata.JSONAPIMetadata',
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_json_api.django_filters.DjangoFilterBackend', # Required to apply filtering to django view sets
    ),
}


CORS_ORIGIN_ALLOW_ALL = False # This must NEVER be true in production!

CORS_ORIGIN_WHITELIST = (
    'localhost:4200','localhost:80', 'localhost:*' # Will change when system is deployed
)

CORS_ALLOW_METHODS = ( # Good to be enforce that we are only getting content to display at this stage
    'GET'
)

# For handling static files via the docker
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(BASE_DIR, '..', 'static')


# For handling media such as images
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'


# To allow resource requests from the development client (Allow-from isnt supported for chrome/firefox)
# X_FRAME_OPTIONS = "ALLOW-FROM https://localhost:4200/"

