# Generated by Django 2.1.3 on 2018-12-04 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('progress', models.FloatField()),
                ('adapter_id', models.PositiveIntegerField()),
                ('adapter_ref', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'milestone_history',
            },
        ),
        migrations.CreateModel(
            name='MilestoneStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OV', 'Overdue'), ('CO', 'Complete'), ('IN', 'In Progress'), ('NO', 'Not Started'), ('BL', 'Blocked'), ('DE', 'Deferred'), ('CA', 'Cancelled'), ('DE', 'Delayed')], default='NO', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'milestone_status',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('vision', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=200)),
                ('teams', models.ManyToManyField(related_name='team_members', to='programmes.Team')),
            ],
            options={
                'db_table': 'team_member',
            },
        ),
        migrations.AddField(
            model_name='milestonehistory',
            name='from_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_from_histories', to='programmes.MilestoneStatus'),
        ),
        migrations.AddField(
            model_name='milestonehistory',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_histories', to='programmes.Milestone'),
        ),
        migrations.AddField(
            model_name='milestonehistory',
            name='to_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_to_histories', to='programmes.MilestoneStatus'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='milestone_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='programmes.MilestoneStatus'),
        ),
        migrations.AddField(
            model_name='goal',
            name='initiatives',
            field=models.ManyToManyField(related_name='goals', to='programmes.Initiative'),
        ),
        migrations.AddField(
            model_name='goal',
            name='problems',
            field=models.ManyToManyField(related_name='goals', to='programmes.Problem'),
        ),
        migrations.AddField(
            model_name='goal',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='programmes.Programme'),
        ),
    ]
