# Generated by Django 2.1.3 on 2018-12-10 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='image',
            field=models.ImageField(upload_to='prp/goals/images'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='image',
            field=models.ImageField(upload_to='prp/programmes/images'),
        ),
    ]
