# Generated by Django 2.1.3 on 2018-12-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0002_auto_20181211_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('OV', 'Overdue'), ('CO', 'Complete'), ('IN', 'In Progress'), ('NO', 'Not Started'), ('BL', 'Blocked'), ('DE', 'Deferred'), ('CA', 'Cancelled'), ('DE', 'Delayed')], default='NO', max_length=2),
        ),
    ]
