# Generated by Django 2.1.3 on 2018-12-11 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0003_initiative_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='prp/benefits/images')),
                ('value', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('unknown', 'Unknown'), ('minor', 'Minor'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='unknown', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('OV', 'Overdue'), ('CO', 'Complete'), ('IN', 'In Progress'), ('NO', 'Not Started'), ('BL', 'Blocked'), ('DF', 'Deferred'), ('CA', 'Cancelled'), ('DE', 'Delayed')], default='NO', max_length=2),
        ),
        migrations.AddField(
            model_name='goal',
            name='benefits',
            field=models.ManyToManyField(related_name='goals', to='programmes.Benefit'),
        ),
    ]
