# Generated by Django 2.1.3 on 2018-12-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0004_auto_20181211_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='value',
            field=models.CharField(max_length=12),
        ),
    ]
