# Generated by Django 2.1.3 on 2018-12-11 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0006_auto_20181211_1741'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='benefit',
            table='benefit',
        ),
    ]
