# Generated by Django 2.1.3 on 2018-12-12 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0007_auto_20181212_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('end_date', models.DateField()),
                ('progress', models.FloatField()),
                ('team_impact', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=8)),
                ('sponsor_impact', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=8)),
                ('pm_impact', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('severe', 'Severe')], default='none', max_length=8)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('OV', 'Overdue'), ('CO', 'Complete'), ('IN', 'In Progress'), ('NO', 'Not Started'), ('BL', 'Blocked'), ('DF', 'Deferred'), ('CA', 'Cancelled'), ('DE', 'Delayed')], default='NO', max_length=2)),
                ('status_description', models.CharField(default='No description', max_length=200)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='programmes.Initiative')),
            ],
        ),
        migrations.AlterField(
            model_name='milestonestatus',
            name='status',
            field=models.CharField(choices=[('OV', 'Overdue'), ('CO', 'Complete'), ('IN', 'In Progress'), ('NO', 'Not Started'), ('BL', 'Blocked'), ('DF', 'Deferred'), ('CA', 'Cancelled'), ('DE', 'Delayed')], default='NO', max_length=2),
        ),
    ]
