# Generated by Django 2.1.3 on 2018-12-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0008_auto_20181213_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='status',
            field=models.CharField(choices=[('Overdue', 'Overdue'), ('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started'), ('Blocked', 'Blocked'), ('Deferred', 'Deferred'), ('Cancelled', 'Cancelled'), ('Delayed', 'Delayed')], default='Not Started', max_length=10),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='status',
            field=models.CharField(choices=[('Overdue', 'Overdue'), ('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started'), ('Blocked', 'Blocked'), ('Deferred', 'Deferred'), ('Cancelled', 'Cancelled'), ('Delayed', 'Delayed')], default='Not Started', max_length=10),
        ),
        migrations.AlterField(
            model_name='milestonestatus',
            name='status',
            field=models.CharField(choices=[('Overdue', 'Overdue'), ('Complete', 'Complete'), ('In Progress', 'In Progress'), ('Not Started', 'Not Started'), ('Blocked', 'Blocked'), ('Deferred', 'Deferred'), ('Cancelled', 'Cancelled'), ('Delayed', 'Delayed')], default='Not Started', max_length=10),
        ),
    ]
