# Generated by Django 2.1.3 on 2018-12-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0010_auto_20181214_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('likelihood', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], default='Very Low', max_length=12)),
                ('impact', models.CharField(choices=[('Very Low', 'Very Low'), ('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High'), ('Very High', 'Very High')], default='Very Low', max_length=12)),
                ('flagged', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'risk',
            },
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='teams',
        ),
        migrations.AddField(
            model_name='teammember',
            name='contactNumber',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image',
            field=models.ImageField(default=None, upload_to='prp/teammembers/images'),
        ),
    ]
