# Generated by Django 2.1.3 on 2018-12-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0011_auto_20181217_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='initiative',
        ),
        migrations.AddField(
            model_name='initiative',
            name='risks',
            field=models.ManyToManyField(related_name='initiatives', to='programmes.Risk'),
        ),
    ]
