# Generated by Django 2.1.3 on 2018-12-16 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0012_auto_20181217_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='initiative',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='programmes.Initiative'),
            preserve_default=False,
        ),
    ]
