# Generated by Django 2.1.3 on 2018-12-16 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0013_deliverable_initiative'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=None, max_length=8)),
                ('impact', models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=None, max_length=8)),
                ('risk_category', models.CharField(choices=[('Minor', 'Minor'), ('Moderate', 'Moderate'), ('Major', 'Major')], default=None, max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=1, max_length=12),
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, serialize=False, to='programmes.RiskCategory'),
            preserve_default=False,
        ),
    ]
