# Generated by Django 2.1.3 on 2018-12-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0014_auto_20181217_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskMitigationStrategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='risk',
            name='risk_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='programmes.RiskCategory'),
        ),
        migrations.AddField(
            model_name='risk',
            name='mitigations',
            field=models.ManyToManyField(related_name='risks', to='programmes.RiskMitigationStrategy'),
        ),
    ]
