# Generated by Django 2.1.3 on 2018-12-18 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0015_auto_20181217_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='initiative',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teammembers', to='programmes.Initiative'),
            preserve_default=False,
        ),
    ]
