# Generated by Django 2.1.3 on 2018-12-18 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0016_teammember_initiative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='contactNumber',
            new_name='contact_number',
        ),
    ]
