# Generated by Django 2.1.3 on 2018-12-18 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0017_auto_20181218_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='initiative',
        ),
        migrations.AddField(
            model_name='teammember',
            name='initiatives',
            field=models.ManyToManyField(related_name='teammembers', to='programmes.Initiative'),
        ),
    ]
