# Generated by Django 2.1.3 on 2018-12-18 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0019_auto_20181218_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='initatives',
            new_name='initiatives',
        ),
    ]
