# Generated by Django 2.1.3 on 2018-12-18 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0022_auto_20181218_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='teammembers',
            new_name='team_members',
        ),
    ]
