# Generated by Django 2.1.3 on 2019-01-09 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0023_auto_20181218_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=1, max_length=8)),
                ('progress', models.FloatField()),
                ('cost', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='initiative',
            name='outputs',
            field=models.ManyToManyField(related_name='initiatives', to='programmes.Outcome'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='cons',
            field=models.TextField(default='bob'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outcome',
            name='pros',
            field=models.TextField(default='bob'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='achieved',
            field=models.BooleanField(default='False'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='benefit',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='programmes.Benefit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='date',
            field=models.DateField(default='2018-12-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='outputs',
            field=models.ManyToManyField(related_name='targets', to='programmes.Outcome'),
        ),
        migrations.AddField(
            model_name='project',
            name='initiatives',
            field=models.ManyToManyField(related_name='projects', to='programmes.Initiative'),
        ),
        migrations.AddField(
            model_name='goal',
            name='projects',
            field=models.ManyToManyField(related_name='goals', to='programmes.Project'),
        ),
    ]
