# Generated by Django 2.1.3 on 2019-01-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0024_auto_20190110_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='date',
            field=models.DateField(default='2018-12-12'),
            preserve_default=False,
        ),
    ]
