# Generated by Django 2.1.3 on 2019-01-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0028_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='initiatives',
        ),
        migrations.AddField(
            model_name='role',
            name='projects',
            field=models.ManyToManyField(related_name='roles', to='programmes.Project'),
        ),
    ]
