# Generated by Django 2.1.3 on 2019-01-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0029_auto_20190110_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='initiatives',
        ),
    ]
