# Generated by Django 2.1.3 on 2019-01-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0033_auto_20190114_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='initiatives',
        ),
        migrations.AddField(
            model_name='initiative',
            name='projects',
            field=models.ManyToManyField(related_name='initiatives', to='programmes.Project'),
        ),
    ]
