# Generated by Django 2.1.3 on 2019-01-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0035_auto_20190114_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('minor', 'Minor'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='Very Low', max_length=8),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.CharField(choices=[('Very Low', 1), ('Low', 2), ('Moderate', 3), ('High', 4), ('Very High', 5)], default='Very Low', max_length=12),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.CharField(choices=[('Very Low', 1), ('Low', 2), ('Moderate', 3), ('High', 4), ('Very High', 5)], default='Very Low', max_length=12),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='impact',
            field=models.CharField(choices=[('Very Low', 1), ('Low', 2), ('Moderate', 3), ('High', 4), ('Very High', 5)], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='likelihood',
            field=models.CharField(choices=[('Very Low', 1), ('Low', 2), ('Moderate', 3), ('High', 4), ('Very High', 5)], default=None, max_length=8),
        ),
    ]
