# Generated by Django 2.1.3 on 2019-01-14 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0036_auto_20190114_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('minor', 'Minor'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default=1, max_length=8),
        ),
        migrations.AlterField(
            model_name='risk',
            name='impact',
            field=models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='risk',
            name='likelihood',
            field=models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=1, max_length=12),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='impact',
            field=models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='likelihood',
            field=models.CharField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')], default=None, max_length=8),
        ),
    ]
