# Generated by Django 2.1.3 on 2019-01-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0040_programme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='slug',
            field=models.SlugField(),
        ),
    ]
