# Generated by Django 2.1.3 on 2019-01-23 20:19

from django.db import migrations, models
import programmes.modelAttributeValidators


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0041_auto_20190115_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverable',
            old_name='status_description',
            new_name='status_message',
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='end_date',
            field=models.DateField(validators=[programmes.modelAttributeValidators.validate_date_not_in_past]),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='progress',
            field=models.FloatField(validators=[programmes.modelAttributeValidators.validate_progress]),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(validators=[programmes.modelAttributeValidators.validate_date_not_in_future]),
        ),
        migrations.AlterField(
            model_name='update',
            name='log',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
