# Generated by Django 2.1.3 on 2019-01-24 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0043_auto_20190124_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='contact_number',
        ),
    ]
