# Generated by Django 2.1.3 on 2019-01-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0044_remove_teammember_contact_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='contact_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='update',
            name='log',
            field=models.CharField(max_length=200),
        ),
    ]
