# Generated by Django 2.1.3 on 2019-01-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0045_auto_20190124_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to='prp/teammembers/images'),
        ),
    ]
