# Generated by Django 2.1.3 on 2019-01-25 02:13

from django.db import migrations, models
import programmes.modelAttributeValidators


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0046_auto_20190124_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='name',
        ),
        migrations.AlterField(
            model_name='initiative',
            name='end_date',
            field=models.DateField(validators=[programmes.modelAttributeValidators.validate_date_not_in_past]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='outputs',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='programmes.Outcome'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='progress',
            field=models.FloatField(validators=[programmes.modelAttributeValidators.validate_progress]),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='risks',
            field=models.ManyToManyField(blank=True, related_name='initiatives', to='programmes.Risk'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(validators=[programmes.modelAttributeValidators.validate_date_not_in_past]),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='prp/projects/images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='progress',
            field=models.FloatField(validators=[programmes.modelAttributeValidators.validate_progress]),
        ),
    ]
