# Generated by Django 2.1.3 on 2019-01-31 23:08

import datetime
from django.db import migrations, models
import programmes.modelAttributeValidators


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0047_auto_20190125_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='risks',
        ),
        migrations.AddField(
            model_name='risk',
            name='initiatives',
            field=models.ManyToManyField(blank=True, related_name='risks', to='programmes.Initiative'),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='adapter_id',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='adapter_ref',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 1)),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 1)),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 1)),
        ),
        migrations.AlterField(
            model_name='programme',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 1)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 1)),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(validators=[programmes.modelAttributeValidators.validate_date_not_in_future], verbose_name=datetime.date(2019, 2, 1)),
        ),
    ]
