# Generated by Django 2.1.3 on 2019-02-01 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0048_auto_20190201_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='risks',
            field=models.ManyToManyField(db_table='app_propertytype_initiatives', to='programmes.Risk'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='initiatives',
            field=models.ManyToManyField(blank=True, related_name='initiative_risks', to='programmes.Initiative'),
        ),
    ]
