# Generated by Django 2.1.3 on 2019-02-01 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0049_auto_20190201_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='members',
            field=models.ManyToManyField(related_name='programmes', to=settings.AUTH_USER_MODEL),
        ),
    ]
