# Generated by Django 2.1.3 on 2019-02-06 08:27

import datetime
from django.db import migrations, models
import programmes.modelAttributeValidators


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0050_programme_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='benefit',
        ),
        migrations.AddField(
            model_name='target',
            name='benefits',
            field=models.ManyToManyField(related_name='targets', to='programmes.Benefit'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='risks',
            field=models.ManyToManyField(blank=True, db_table='app_propertytype_initiatives', to='programmes.Risk'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 6)),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 6)),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 6)),
        ),
        migrations.AlterField(
            model_name='programme',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 6)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 6)),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(validators=[programmes.modelAttributeValidators.validate_date_not_in_future], verbose_name=datetime.date(2019, 2, 6)),
        ),
    ]
