# Generated by Django 2.1.5 on 2019-02-11 07:31

import datetime
from django.db import migrations, models
import programmes.modelAttributeValidators


class Migration(migrations.Migration):

    dependencies = [
        ('programmes', '0051_auto_20190206_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initiative',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 11)),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 11)),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 11)),
        ),
        migrations.AlterField(
            model_name='programme',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 11)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name=datetime.date(2019, 2, 11)),
        ),
        migrations.AlterField(
            model_name='update',
            name='date',
            field=models.DateField(validators=[programmes.modelAttributeValidators.validate_date_not_in_future], verbose_name=datetime.date(2019, 2, 11)),
        ),
    ]
